### ISSUE TITLE
SKU API

### ISSUE THREAD

**Issue by carlaiau** [Semantics3/semantics3-php#16]
Great work! Is there any potential for SKU API implementation?

**Comment by ducnguyenhuy** [comment]
@carlaiau You can see SKU API on left navigation at documentation link here http://docs.semantics3.com/v1.0/docs

**Comment by carlaiau** [comment]
But it's not built into the PHP library? Or is it?

**Comment by ducnguyenhuy** [comment]
Check it https://github.com/Semantics3/semantics3-php

**Comment by carlaiau** [comment]
I'm using it for querying products API, but don't know how to use it for querying SKU API

**Comment by ducnguyenhuy** [comment]
I did not query SKU API before but as I see code here https://github.com/Semantics3/semantics3-php/blob/master/lib/Semantics3/Products.php, I think you need to call `query()` function and give endpoint `skus` and also query params to do that. And note that you need to purchase a plan to do query SKUS, It's limited to Demo plan.

**Comment by carlaiau** [comment]
Thanks for the guidance, will try it out. Yeap, we're on a paid plan.

**Comment by ducnguyenhuy** [comment]
Run your query on playground https://dashboard.semantics3.com/p#/playground first before moving it into your code. Btw, I did not use Semantics3 2 years ago.
