### ISSUE TITLE
Parse error: syntax error, unexpected  on ApiConnector.php on line 14

### ISSUE THREAD

**Issue by Nisarahmadaim** [Semantics3/semantics3-php#27]
Hi Guys,

i have downloaded your API code from Git  https://github.com/Semantics3/semantics3-php
but when i have run it on my local machine i got this Error  " Parse error: syntax error, unexpected '[' in D:\xampp\htdocs\sem\lib\Semantics3\ApiConnector.php on line 14 "

**Comment by amarnus** [comment]
@Nisarahmadaim: This must be because of your PHP version. The minimum PHP version that we need is 5.4. It was incorrectly mentioned as 5.2 earlier. I have [fixed this](https://github.com/Semantics3/semantics3-php/blob/master/composer.json#L18) now. Sorry about that!
